-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 18:29:14 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema music
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `music` ;

-- -----------------------------------------------------
-- Table `music`.`album_art`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music`.`album_art` (
  `album_id` INT NOT NULL COMMENT '',
  `album_name` VARCHAR(75) NOT NULL COMMENT '',
  `location` VARCHAR(500) NOT NULL COMMENT '',
  PRIMARY KEY (`album_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
